"""create test runs table

Revision ID: 71e858e484a7
Revises: 
Create Date: 2026-09-29 13:13:46.221545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e858e484a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_commit_sha'), 'test_runs', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_test_runs_id'), 'test_runs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_runs_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_commit_sha'), table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ###
